name: sem_store
description: "vanyasem's iOS app store."
publish_to: 'none'
version: 0.1.0

environment:
  flutter: ^3.35.0
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  fl_common_lint: ^1.8.0

flutter:
  uses-material-design: true
